#!/usr/bin/env python3
"""
اعتبارسنجی متقابل موتور طراحی با scipy.

این اسکریپت بردارهای مرجع (پاسخ فرکانسی SOS طراحی‌شده با scipy) را تولید و
در tests/ref/design_reference.json + design_reference.h ذخیره می‌کند.
تست C (test_design.c) همان بردارها را با خروجی کتابخانه مقایسه می‌کند.

اجرا:
    python3 tests/reference/validate_scipy.py     (بازتولید مراجع)
    make test                                    (اجرای تست‌ها)

نیازمندی: numpy, scipy
"""
import numpy as np
import json
from scipy.signal import butter, cheby1, cheby2, ellip, bessel, sosfreqz

FS = 48000.0
FC = 1000.0
cases = []


def add(name, sos, freqs):
    w = np.array([2 * np.pi * f / FS for f in freqs])
    _, H = sosfreqz(sos, worN=w)
    cases.append({"name": name, "freqs": list(freqs), "mag": np.abs(H).tolist()})


def main():
    # --- Butterworth ---
    add("butter_lp2", butter(2, FC, fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    add("butter_lp4", butter(4, FC, fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    add("butter_hp3", butter(3, FC, "hp", fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    add("butter_bp2", butter(2, [500, 2000], "bp", fs=FS, output="sos"),
        [0, 300, 500, 1000, 2000, 4000, 24000])
    add("butter_bs2", butter(2, [500, 2000], "bs", fs=FS, output="sos"),
        [0, 300, 500, 1000, 2000, 4000, 24000])
    # --- Chebyshev I ---
    add("cheby1_lp3", cheby1(3, 1.0, FC, fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    add("cheby1_lp4", cheby1(4, 0.5, FC, fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    add("cheby1_hp2", cheby1(2, 1.0, FC, "hp", fs=FS, output="sos"), [0, 500, 1000, 2000, 8000, 24000])
    # --- Chebyshev II ---
    add("cheby2_lp3", cheby2(3, 30.0, FC, fs=FS, output="sos"),
        [0, 500, 1000, 2000, 3000, 8000, 24000])
    add("cheby2_bp2", cheby2(2, 40.0, [500, 2000], "bp", fs=FS, output="sos"),
        [0, 300, 500, 1000, 2000, 4000, 24000])
    # --- Elliptic ---
    add("ellip_lp3", ellip(3, 1.0, 40.0, FC, fs=FS, output="sos"),
        [0, 500, 1000, 1200, 1500, 2000, 8000, 24000])
    add("ellip_lp5", ellip(5, 0.5, 60.0, FC, fs=FS, output="sos"),
        [0, 500, 1000, 1200, 1500, 3000, 24000])
    add("ellip_bs2", ellip(2, 1.0, 40.0, [500, 2000], "bs", fs=FS, output="sos"),
        [0, 300, 500, 1000, 2000, 4000, 24000])
    # --- Bessel ---
    add("bessel_lp3", bessel(3, FC, "lp", norm="phase", fs=FS, output="sos"),
        [0, 500, 1000, 2000, 8000, 24000])
    add("bessel_lp4", bessel(4, FC, "lp", norm="phase", fs=FS, output="sos"),
        [0, 500, 1000, 2000, 8000, 24000])

    json.dump({"fs": FS, "fc": FC, "cases": cases},
              open("tests/ref/design_reference.json", "w"), indent=1)

    # تولید هدر C
    lines = ["/* Auto-generated by validate_scipy.py — do not edit */",
             "#ifndef DSP_TEST_DESIGN_REF_H", "#define DSP_TEST_DESIGN_REF_H",
             "#define REF_FS 48000.0", "#define REF_FC 1000.0"]
    for c in cases:
        lines.append("static const double ref_%s_freqs[] = {%s};"
                     % (c["name"], ",".join(str(int(f)) for f in c["freqs"])))
        lines.append("static const double ref_%s_mag[] = {%s};"
                     % (c["name"], ",".join("%.15e" % v for v in c["mag"])))
        lines.append("static const int ref_%s_n = %d;" % (c["name"], len(c["mag"])))
    lines.append("#endif")
    open("tests/ref/design_reference.h", "w").write("\n".join(lines))
    print("OK — %d reference cases written" % len(cases))


if __name__ == "__main__":
    main()
